# Generated by Django 5.1.5 on 2025-02-03 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer', 'Computer'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Electronics', 'Electronics'), ('Electrical', 'Electrical'), ('Agriculture', 'Agriculture')], default=True, max_length=50, null=True)),
                ('subject', models.CharField(choices=[('Minor Project', 'Minor Project'), ('Artificial Intelligence', 'Artificial Intelligence'), ('DBMS', 'DBMS'), ('Embedded System', 'Embedded System'), ('Operating System', 'Operating System'), ('Economics', 'Economics')], default=True, max_length=100, null=True)),
                ('year', models.CharField(choices=[('2024-2025', '2024-2025'), ('2025-2026', '2025-2026')], default=True, max_length=10, null=True)),
                ('semester', models.CharField(choices=[('Semester-1', 'Semester-1'), ('Semester-2', 'Semester-2'), ('Semester-3', 'Semester-3'), ('Semester-4', 'Semester-4'), ('Semester-5', 'Semester-5'), ('Semester-6', 'Semester-6')], default=True, max_length=20, null=True)),
                ('student_id', models.CharField(default=True, max_length=50, null=True, unique=True)),
                ('student_name', models.CharField(default=True, max_length=100, null=True)),
                ('class_group', models.CharField(choices=[('AB', 'AB'), ('CD', 'CD')], default=True, max_length=10, null=True)),
                ('teacher_name', models.CharField(default=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Student_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default=False, max_length=50, unique=True)),
                ('name', models.CharField(default=False, max_length=100)),
                ('image_path', models.CharField(default=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], default=False, max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('time', models.TimeField(default=False)),
                ('student', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
            options={
                'unique_together': {('student', 'date', 'session')},
            },
        ),
    ]
