# Generated by Django 5.1.5 on 2025-02-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_status_attendance_afternoon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='afternoon',
            new_name='afternoon_attendance',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='morning',
            new_name='morning_attendance',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_status',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Student_attendance',
        ),
    ]
