# Generated by Django 5.1.5 on 2025-02-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendance_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
