# Generated by Django 5.1.5 on 2025-02-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_password_remove_student_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='afternoon_attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10),
        ),
    ]
