# Generated by Django 5.1.3 on 2025-02-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_alter_attendance_afternoon_attendance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="total_attendance",
            field=models.FloatField(default=0.0),
        ),
    ]
