# Generated by Django 5.1.3 on 2025-02-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_attendance_total_attendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="total_attendance",
        ),
    ]
